tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "secondary-fixed-dim": "#b3ccc3",
                "outline": "#707975",
                "on-surface-variant": "#3f4945",
                "on-background": "#1a1c1c",
                "inverse-primary": "#94d3c1",
                "inverse-on-surface": "#f1f1f1",
                "surface-container-high": "#e8e8e8",
                "on-secondary-container": "#506760",
                "primary-fixed-dim": "#94d3c1",
                "surface-container-highest": "#e2e2e2",
                "surface-bright": "#f9f9f9",
                "on-error": "#ffffff",
                "on-tertiary": "#ffffff",
                "primary": "#024127",
                "error": "#ba1a1a",
                "tertiary": "#4e2013",
                "on-secondary": "#ffffff",
                "surface-variant": "#e2e2e2",
                "on-tertiary-fixed": "#370e04",
                "on-error-container": "#93000a",
                "surface-container-low": "#f3f3f3",
                "on-primary": "#ffffff",
                "on-primary-fixed": "#00201a",
                "primary-fixed": "#afefdd",
                "tertiary-fixed-dim": "#ffb5a1",
                "on-tertiary-fixed-variant": "#6d382a",
                "secondary": "#4c635c",
                "on-primary-container": "#7ebdac",
                "surface-dim": "#dadada",
                "on-secondary-fixed-variant": "#354b45",
                "secondary-fixed": "#cfe8df",
                "inverse-surface": "#2f3131",
                "error-container": "#ffdad6",
                "surface-tint": "#29695b",
                "surface-container-lowest": "#ffffff",
                "tertiary-fixed": "#ffdbd1",
                "on-secondary-fixed": "#081f1a",
                "background": "#f9f9f9",
                "tertiary-container": "#693527",
                "primary-container": "#004d40",
                "surface": "#f9f9f9",
                "on-primary-fixed-variant": "#065043",
                "on-tertiary-container": "#e89f8c",
                "outline-variant": "#bfc9c4",
                "secondary-container": "#cce5dc",
                "surface-container": "#eeeeee",
                "on-surface": "#1a1c1c"
            },
            fontFamily: {
                "headline": ["Newsreader", "serif"],
                "body": ["Manrope", "sans-serif"],
                "label": ["Manrope", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },
}